train: /home/rupesh_pabba/rupeshpabba/pothole2/detection/train/images
val: /home/rupesh_pabba/rupeshpabba/pothole2/detection/valid/images
test: /home/rupesh_pabba/rupeshpabba/pothole2/detection/test/images

nc: 1
names: ['pothole']

batch_size: 16


